# Generated by Django 3.1.2 on 2020-10-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='parents',
            field=models.ManyToManyField(related_name='children', to='api.Device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('COMPUTER', 'COMPUTER'), ('REPEATER', 'REPEATER')], max_length=10),
        ),
    ]
